package com.healthupgrades.auth.domain.model;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.Optional;
import java.util.UUID;

/**
 * The opaque credential a browser holds in its refresh cookie: {@code <sessionId>.<secret>}.
 *
 * <p>Opaque on purpose. It is not a JWT and carries no claims — everything about the session is a
 * column, so there is nothing in the value for a holder to read and nothing to keep in step with the
 * row. The session id is in it only so the server knows which row to lock; the secret is what proves
 * the holder is the one the row was issued to.
 *
 * <p>Only the SHA-256 of the whole value is stored. A database copy therefore yields nothing usable:
 * the stored digest cannot be presented, and it cannot be reversed into something that can. Hashing the
 * <em>whole</em> value rather than the secret alone binds the secret to its session, so a secret lifted
 * from one row cannot be replayed against another.
 *
 * <p>SHA-256 without a work factor is deliberate, and the opposite of the choice made for passwords.
 * This is 256 bits of output from a cryptographic random source, not something a person picked: there
 * is no dictionary to walk and no cost parameter that would make brute force any less impossible. A
 * per-request BCrypt here would buy nothing and cost a refresh.
 *
 * @param sessionId the session the credential belongs to
 * @param secret    the random half, base64url, generated by {@code SecretGeneratorPort}
 */
public record RefreshToken(UUID sessionId, String secret) {

    /** Separates the two halves. Not a character base64url produces, so the split is unambiguous. */
    private static final char SEPARATOR = '.';

    public RefreshToken {
        if (sessionId == null || secret == null || secret.isBlank()) {
            throw new IllegalArgumentException("a refresh token needs a session id and a secret");
        }
    }

    /**
     * Reads a cookie value back into a token.
     *
     * <p>Answers empty rather than throwing for anything malformed. The value arrives from a browser and
     * is as unvalidated as any other request input; a caller that cannot parse it has learned all it
     * needs, which is that this is not a credential this server issued.
     *
     * @param value the raw cookie value
     * @return the parsed token, or empty if it is not in the issued shape
     */
    public static Optional<RefreshToken> parse(String value) {
        if (value == null) {
            return Optional.empty();
        }
        int separator = value.indexOf(SEPARATOR);
        if (separator <= 0 || separator == value.length() - 1) {
            return Optional.empty();
        }
        try {
            return Optional.of(new RefreshToken(
                    UUID.fromString(value.substring(0, separator)),
                    value.substring(separator + 1)));
        } catch (IllegalArgumentException notAToken) {
            return Optional.empty();
        }
    }

    /** The value as it travels in the cookie. */
    public String value() {
        return sessionId + String.valueOf(SEPARATOR) + secret;
    }

    /**
     * The digest stored against the session, and the only form of this credential the database ever sees.
     *
     * @return the SHA-256 of {@link #value()}
     */
    public byte[] hash() {
        try {
            return MessageDigest.getInstance("SHA-256").digest(value().getBytes(StandardCharsets.UTF_8));
        } catch (NoSuchAlgorithmException impossible) {
            // Every JVM is required to provide SHA-256. If this ever throws, the platform is broken in a
            // way no fallback here could sensibly paper over.
            throw new IllegalStateException("SHA-256 is unavailable", impossible);
        }
    }
}
