package com.healthupgrades.common.observability;

import io.micrometer.tracing.Span;
import io.micrometer.tracing.Tracer;

import java.util.Optional;

/**
 * Reads the trace id of the work currently in flight, or nothing when there is none.
 *
 * <p>The id is the key that joins a failure a user reports to the log lines that produced it. It is
 * generated by Micrometer's tracing (see {@code docs/ADRs/ADR-007-request-correlation-through-micrometer-tracing.md}),
 * reaches the log line through the MDC without any call site asking for it, and is read back here only
 * where it has to be handed to a client — the {@code X-Trace-Id} response header and the error body.
 *
 * <p>"No id" is a normal answer, not a failure, and it arrives in three different shapes that all have
 * to be handled:
 *
 * <ul>
 *   <li>a real tracer with no span in scope returns {@code null} from {@link Tracer#currentSpan()};</li>
 *   <li>{@link Tracer#NOOP} — what a unit test gets, and what is wired when tracing is disabled —
 *       returns a span whose trace id is the empty string;</li>
 *   <li>an invalid OpenTelemetry context has a trace id that is all zeros.</li>
 * </ul>
 */
public final class CorrelationId {

    /** OpenTelemetry's invalid trace id: 32 zeros. A span carrying it identifies nothing. */
    private static final String INVALID_TRACE_ID = "0".repeat(32);

    private CorrelationId() {
    }

    /**
     * @param tracer the tracer to ask; never null, since a {@code Tracer} bean is always wired
     * @return the current trace id, or empty when nothing is being traced
     */
    public static Optional<String> of(Tracer tracer) {
        Span span = tracer.currentSpan();
        if (span == null) {
            return Optional.empty();
        }
        String traceId = span.context().traceId();
        if (traceId == null || traceId.isBlank() || INVALID_TRACE_ID.equals(traceId)) {
            return Optional.empty();
        }
        return Optional.of(traceId);
    }
}
